version: '3.7'

services:
  backend:
    build: ./backend
    restart: always
    ports:
      - 4000:4000
    depends_on:
      - rabbit
    volumes:
      - ./backend/uploads:/app/uploads
    env_file:
      - ./env/backend.env
    environment:
      - RABBITMQ_URI=amqp://jktech:rabbitMq@rabbit:5672

  ingestion:
    build: ./ingestion
    restart: always
    depends_on:
      - rabbit
      - backend
    env_file:
      - ./env/ingestion.env
    environment:
      - RABBITMQ_URI=amqp://jktech:rabbitMq@rabbit:5672

  postgres:
    image: postgres:13
    container_name: postgres_db
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: jk_db
      POSTGRES_USER: jk_user
      POSTGRES_PASSWORD: jk_password
    volumes:
      - postgres_data:/var/lib/postgresql/data

  rabbit:
    image: rabbitmq:3-management
    container_name: rabbitmq
    restart: always
    environment:
      RABBITMQ_DEFAULT_USER: jktech
      RABBITMQ_DEFAULT_PASS: rabbitMq
    ports:
      - '5672:5672'
      - '15672:15672'

volumes:
  postgres_data: {}
