version: '3.7'

services:
  postgres:
    image: postgres:13
    container_name: postgres_db
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: jk_db
      POSTGRES_USER: jk_user
      POSTGRES_PASSWORD: jk_password
    volumes:
      - postgres_data:/var/lib/postgresql/data

  rabbit:
    image: rabbitmq:3-management
    container_name: rabbitmq
    restart: always
    environment:
      RABBITMQ_DEFAULT_USER: jktech
      RABBITMQ_DEFAULT_PASS: rabbitMq
    ports:
      - '5672:5672'
      - '15672:15672'  # Web management UI

volumes:
  postgres_data:
